# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"

inherit distutils


DESCRIPTION="Guess the natural language of a text"
HOMEPAGE="http://code.google.com/p/guess-language"
SRC_URI="http://pypi.python.org/packages/source/g/guess-language/${P}.tar.gz"

LICENSE="LGPL-2.1"
KEYWORDS="~x86 ~amd64"
SLOT="0"
IUSE=""


PYTHON_MODNAME="guess_language"

