# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="HTML parser based on the WHAT-WG Web Applications 1.0("HTML5") specifcation"
HOMEPAGE="http://code.google.com/p/html5lib/"
SRC_URI="http://pypi.python.org/packages/source/h/html5lib/${P}.tar.gz"

LICENSE="MIT"
KEYWORDS="~x86"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="${DEPEND}"


