# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Python HTTP for Humans."
HOMEPAGE="http://python-requests.org"
SRC_URI="http://pypi.python.org/packages/source/r/requests/${P}.tar.gz"

LICENSE="Apache-2.0"
KEYWORDS="~x86"
SLOT="0"
IUSE=""



