--- src/makefile.unix	2013-08-02 14:29:16.000000000 +1000
+++ src/makefile.unix-new	2013-11-27 15:53:42.299392889 +1100
@@ -39,6 +39,7 @@
    -l boost_filesystem$(BOOST_LIB_SUFFIX) \
    -l boost_program_options$(BOOST_LIB_SUFFIX) \
    -l boost_thread$(BOOST_LIB_SUFFIX) \
+   -l boost_chrono$(BOOST_LIB_SUFFIX) \
    -l db_cxx$(BDB_LIB_SUFFIX) \
    -l ssl \
    -l crypto
